apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        jrcampos55:
          repos:
            jx3-minikube-vault:
              required_status_checks:
                contexts:
                - promotion-build
            spring-boot-http-gradle-jenkins-x:
              required_status_checks:
                contexts:
                - pr-build
      protect-tested-repos: true
    github:
      LinkURL: null
    plank: {}
    pod_namespace: jx
    postsubmits:
      jrcampos55/jx3-minikube-vault:
      - agent: tekton
        branches:
        - master
        name: promotion
        skip_report: true
      jrcampos55/spring-boot-http-gradle-jenkins-x:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
    presubmits:
      jrcampos55/jx3-minikube-vault:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jrcampos55/spring-boot-http-gradle-jenkins-x:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jrcampos55/jx3-minikube-vault: merge
        jrcampos55/spring-boot-http-gradle-jenkins-x: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jrcampos55/jx3-minikube-vault
        - jrcampos55/spring-boot-http-gradle-jenkins-x
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jrcampos55/jx3-minikube-vault
        - jrcampos55/spring-boot-http-gradle-jenkins-x
      target_url: http://deck-jx.192.168.99.100.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
